name: layered
description: "A cross-platform relaxing puzzle game that challenges players to sort fruit slabs into bottles following stacking rules across 100 progressively difficult levels — fully offline."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/